#pragma once

#include <assets/basset_types.h>

#include "bresources/bresource_types.h"

bresource_material_type basset_material_type_to_bresource(basset_material_type type);
basset_material_type bresource_material_type_to_basset(bresource_material_type type);

bresource_material_model basset_material_model_to_bresource(basset_material_model model);
basset_material_model bresource_material_model_to_basset(bresource_material_model model);

bresource_material_texture_map basset_material_tex_map_to_bresource(basset_material_texture_map map);
basset_material_texture_map bresource_material_tex_map_to_basset(bresource_material_texture_map map);

bresource_material_texture_map_channel basset_material_tex_map_channel_to_bresource(basset_material_texture_map_channel channel);
basset_material_texture_map_channel bresource_material_tex_map_channel_to_basset(bresource_material_texture_map_channel channel);

bresource_material_texture basset_material_texture_to_bresource(basset_material_texture texture);
basset_material_texture bresource_material_texture_to_basset(bresource_material_texture texture);

bresource_material_sampler basset_material_sampler_to_bresource(basset_material_sampler sampler);
basset_material_sampler bresource_material_sampler_to_basset(bresource_material_sampler sampler);
