#pragma once

#include <assets/basset_types.h>

#include "bresource_types.h"
#include "resources/resource_types.h"

BAPI bresource_texture_format image_format_to_texture_format(basset_image_format format);
BAPI basset_image_format texture_format_to_image_format(bresource_texture_format format);
BAPI u8 channel_count_from_texture_format(bresource_texture_format format);

BAPI texture_channel bresource_texture_map_channel_to_texture_channel(bresource_material_texture_map_channel channel);
BAPI bresource_material_texture_map_channel texture_channel_to_bresource_texture_map_channel(texture_channel channel);

BAPI material_type bresource_material_type_to_material_type(bresource_material_type type);
BAPI bresource_material_type material_type_to_bresource_material_type(bresource_material_type type);
BAPI material_model bresource_material_model_to_material_model(bresource_material_model model);
BAPI bresource_material_model material_model_to_bresource_material_model(material_model model);
